### ISSUE TITLE
Can't play Reolink Home Hub videos

### ISSUE THREAD

**Issue by RandyT65** [home-assistant/home-assistant.github.io#36276]
### Feedback

I can see the folders and media files under the Media tab but when I click to play one, nothing happens,.

### URL

https://www.home-assistant.io/integrations/reolink/

### Version

2024.12.1

**Comment by starkillerOG** [comment]
Thanks for reporting this issue, I am aware of the issue and can reproduce it on my setup.
Will look into it some more, but it may take some time.
It was working before, but the latest Home Hub firmware broke it.
When downgrading the Home Hub firmware it works again, so it definetly has to do with something that changed in the firmware and the video files, but I am not sure what and how to resolve it yet.

**Comment by RandyT65** [comment]
Thanks for your reply.  I’m fairly new to Home Assistant and it’s pretty impressive to receive a personal reply from one of the developers!  Good luck fixing this bug.Randy TreeceSent from my iPad ProOn Dec 11, 2024, at 6:43 AM, starkillerOG ***@***.***> wrote:﻿
Thanks for reporting this issue, I am aware of the issue and can reproduce it on my setup.
Will look into it some more, but it may take some time.
It was working before, but the latest Home Hub firmware broke it.
When downgrading the Home Hub firmware it works again, so it definetly has to do with something that changed in the firmware and the video files, but I am not sure what and how to resolve it yet.

**Comment by starkillerOG** [comment]
This PR will at least solve SSL issues and acces when not on the local network regarding playback of Reolink media: https://github.com/home-assistant/core/pull/133916

However the issue with the Home Hub firmware has not been solved yet although I now know what is wrong with the files: the mime-type is video/x-flv instead of video/mp4

**Comment by starkillerOG** [comment]
If you appreciate the reolink integration and want to support its development, please consider [sponsering](https://github.com/sponsors/starkillerOG) the upstream library or purchase Reolink products through [this affiliate link](https://reolink.pxf.io/q44QWq).

**Comment by starkillerOG** [comment]
I now also solved the issue with the Home Hub, using a alternative method I restored the ability to playback video on the Home Hub.

Will let you know when the fix makes it in a HA release

**Comment by RandyT65** [comment]
That’s great!  Thanks for the updates.

Randy Treece

**Comment by starkillerOG** [comment]
The PR which includes part of the fix has been merged and will be included in HA 2025.1.0 which will be released Jan 3th.
This will restore the playback capability in HA when using a Home Hub.
However the fix for SSL issues and playing recordings when not on the LAN has not been merged yet and will have to wait untill HA 2025.2.0.

**Comment by RandyT65** [comment]
Thanks again and I will use your affiliate link when I buy a couple more cams this spring.

Randy Treece

**Comment by starkillerOG** [comment]
HA 2025.1.1 is now available and should resolve all issues.
In the end also the fixes for SSL and playing when not on the LAN made it into HA 2025.1.1.

So if you still experiance any issues after updating, please let me know.

**Comment by RandyT65** [comment]
Hey I did the update and it still isn’t working for me. Randy TreeceSent from my iPhoneOn Jan 7, 2025, at 3:51 PM, starkillerOG ***@***.***> wrote:﻿
HA 2025.1.1 is now available and should resolve all issues.
In the end also the fixes for SSL and playing when not on the LAN made it into HA 2025.1.1.
So if you still experiance any issues after updating, please let me know.

**Comment by starkillerOG** [comment]
@RandyT65 could you share a diagnostic info file for the Reolink integration?
https://www.home-assistant.io/docs/configuration/troubleshooting/#download-diagnostics

Do you see any errors in the logs?

**Comment by RandyT65** [comment]
I’d be happy to if you tell me how to get the logs.  I’m fairly new with HA.

Randy Treece

**Comment by starkillerOG** [comment]
See https://www.home-assistant.io/integrations/system_log/

Settings->system->logging.

And see the link in my previous message for diagnostic info

**Comment by RandyT65** [comment]
Attachments available until Feb 8, 2025
Gotcha.  See if these are what you need.
Click to Download
 <https://www.icloud.com/attachment/?u=https%3A%2F%2Fcvws.icloud-content.com%2FB%2FAYOaGBtY5NebB4mbfohHqfjmJucbAbX3ROtP7P_IUI3k5yJAm62YES7X%2F%24%7Bf%7D%3Fo%3DAjKUHhcWmi7UFL6srz777Gc00B3oQJmQ6EfqZpO_pPp2%26v%3D1%26x%3D3%26a%3DCAogJ27a4PP4HdtLEbW3rBF1gZnorm7xvEUg1s1FdUvrdbMSeBCKsv7WxDIYisL5qs4yIgEAKgkC6AMA_0kEQdpSBOYm5xtaBJgRLtdqJuw7oM8t0ZgLIZuF8ra9hxx0gG_X44drZUFZGr9NZAwshv6HKn3EciaI-XNe6-5aM__FessW4MQvgRBB1OZhr9x1knGUZLzs-5Mh9Jo85g%26e%3D1739014955%26fl%3D%26r%3D76C8FA72-20FF-42F1-8878-BDF9B37EC51C-1%26k%3D%24%7Buk%7D%26ckc%3Dcom.apple.largeattachment%26ckz%3D57AA0AD1-304E-4A7E-80EE-3F68A6C084C6%26p%3D103%26s%3D8KoqlLZ0rtSE8eMdi2vg7E8tVyA&uk=syVjRcbGQKWAVKeCHbjkxg&f=home-assistant_2025-01-09T11-40-14.407Z.log&sz=43986892>home-assistant_2025-01-09T11-40-14.407Z.log
44 MB
Click to Download
 <https://www.icloud.com/attachment/?u=https%3A%2F%2Fcvws.icloud-content.com%2FB%2FAb2VokAtYcl7bhU9E7bx7iTQxwpzAaRoz4U6PEm0j1PdUAk2csljw5-p%2F%24%7Bf%7D%3Fo%3DArROYjwi9yrKtleZTY0kXP6jOAl6D8A7eEl6TtE8b5TG%26v%3D1%26x%3D3%26a%3DCAogh7KsbLXQdE_QR1-HrVl3KBxo_s7-ZGJdAg7kAi3H2q8SeBC2tP7WxDIYtsT5qs4yIgEAKgkC6AMA_xgFA4RSBNDHCnNaBGPDn6lqJhK-rNK0sJNZ7HmV8njXQKGXWA6zdR97wagE2cT4vXF52ydxHtH4cibYvxPVA2b_V7gDZH549cCjb3EvooL9GaJad0twN1rsrSLphlMymA%26e%3D1739014955%26fl%3D%26r%3DD08685A7-CEB1-4B1B-8ACD-017C4F53AB15-1%26k%3D%24%7Buk%7D%26ckc%3Dcom.apple.largeattachment%26ckz%3D57AA0AD1-304E-4A7E-80EE-3F68A6C084C6%26p%3D103%26s%3DRWp32LpfKiONfXhY1ev-SuSn7qk&uk=mgjjSusPXFHyUHmB0PXEvg&f=config_entry-reolink-01JDAN87KW4XV0C9EMB8EFACHD.json&sz=93322>config_entry-reolink-01JDAN87KW4XV0C9EMB8EFACHD.json
93 KB


Randy Treece

**Comment by starkillerOG** [comment]
I don't see anything strange in your diagnostics file.

I do see this error in your log:
`2025-01-08 09:26:30.557 WARNING (MainThread) [homeassistant.components.reolink.views] Reolink playback error while getting mp4: Timeout on reading data from socket`
It happens twice, both probably when you were trying to play a playback video. However at that time the debug logging of the reolink integration was turned off.
This error is most likely the cause of your problems.

Could you enable debug logging of the reolink integration, then try to play a few playback recordings inside HomeAssistant, then disable debug logging angain and post the resulting log.txt file here?
https://www.home-assistant.io/docs/configuration/troubleshooting/#enabling-debug-logging

**Comment by RandyT65** [comment]
Is this what you’re looking for?
￼

Randy Treece

**Comment by RandyT65** [comment]
Any updates?  This still isn’t working for me.

Randy Treece

**Comment by starkillerOG** [comment]
Please share the debug log as a .log file on github, replaying by email does not work.

**Comment by starkillerOG** [comment]
Do you perhaps have encryption enabled on the Reolink Home Hub?

**Comment by RandyT65** [comment]
I zipped the log files so see if this works and no, I do not have encryption on.  

Thanks
￼

Randy Treece
